//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Album
    {
        public int AlbumID { get; set; }
        [Display(Name = "Album Title")]
        public string AlbumTitle { get; set; }
        public int ArtistID { get; set; }
        [Display(Name = "Date Published")]
        public System.DateTime PubDate { get; set; }
        [Display(Name = "Album Art")]
        public string AlbumArt { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
